# Generated by Django 6.0.6 on 2026-07-26 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ پرداخت.', max_digits=12, verbose_name='مبلغ')),
                ('payment_type', models.CharField(choices=[('ORDER', 'Order'), ('WALLET_CHARGE', 'Wallet Charge')], help_text='مشخص می\u200cکند پرداخت مربوط به سفارش یا شارژ کیف پول است.', max_length=30, verbose_name='نوع پرداخت')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', help_text='وضعیت فعلی پرداخت.', max_length=20, verbose_name='وضعیت پرداخت')),
                ('gateway', models.CharField(choices=[('zarinpal', 'ZarinPal')], default='zarinpal', help_text='درگاه مورد استفاده برای انجام پرداخت.', max_length=30, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, db_index=True, help_text='شناسه Authority دریافتی از درگاه پرداخت.', max_length=255, null=True, unique=True, verbose_name='Authority')),
                ('ref_id', models.CharField(blank=True, db_index=True, help_text='شماره مرجع (Ref ID) پس از پرداخت موفق.', max_length=255, null=True, verbose_name='شماره مرجع')),
                ('object_id', models.PositiveBigIntegerField(help_text='شناسه موجودیت مرتبط با این پرداخت.', verbose_name='شناسه مرجع')),
                ('content_type', models.ForeignKey(help_text='نوع موجودیتی که این پرداخت به آن تعلق دارد.', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='نوع مرجع')),
                ('user', models.ForeignKey(help_text='کاربری که این پرداخت را ایجاد کرده است.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
