version: "3.9"

services:

  db:
    image: postgres:16-alpine
    container_name: postgres_shop1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: parham
      POSTGRES_PASSWORD: paripari85
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_shop1
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pg_pass

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq_shop1
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:8-alpine
    container_name: redis_shop1
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight_shop1
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "5540:5540"

  elasticsearch:
    image: elastic/elasticsearch:8.19.19
    container_name: elasticsearch_shop1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:9.4.4
    container_name: kibana_shop1
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  postgres-data:
  redis-data:
  elasticsearch-data: