services:

  db:
    image: postgres:16-alpine
    container_name: postgres_shop1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=online_shop
      - POSTGRES_USER=parham
      - POSTGRES_PASSWORD=paripari85
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container_shop1
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
    ports:
      - "5050:80"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:4.2-alpine
    container_name: rabbitmq_shop1
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:8-alpine
    container_name: redis_shop1
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: