# Generated by Django 6.0.6 on 2026-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AddIndex(
            model_name='productsmodel',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_55e20c_idx'),
        ),
        migrations.AddIndex(
            model_name='productsmodel',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_3355a0_idx'),
        ),
        migrations.AddIndex(
            model_name='productsmodel',
            index=models.Index(fields=['-sales_count'], name='products_pr_sales_c_0eb114_idx'),
        ),
    ]
