# Generated by Django 6.0.6 on 2026-07-25 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsmodel_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('percent', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='روز شروع')),
                ('end_date', models.DateTimeField(verbose_name='روز پایان')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='فایل ها'),
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=580)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='products.productsmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'کامنت ',
                'verbose_name_plural': 'کامنت ',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'product'], name='products_co_user_id_ab3f76_idx')],
            },
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_liked', to='products.productsmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک ',
                'verbose_name_plural': 'لایک ',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'user'], name='products_li_product_7044dd_idx')],
            },
        ),
    ]
