# Generated by Django 6.0.6 on 2026-07-27 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_ordermodel_orderitemmodel_delete_userorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactioans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('order', 'پرداخت سفارش'), ('wallet_charge', 'شارژ کیف پول')], max_length=20, verbose_name='نوع تراکنش')),
                ('gateway', models.CharField(default='zarinpal', max_length=50, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(max_length=100, unique=True, verbose_name='کد پیگیری درگاه (Authority)')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه\u200cی مرجع تراکنش بانکی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('callback_received', 'بازگشت از درگاه'), ('verified', 'تأیید شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('total_amount', models.PositiveBigIntegerField(help_text='مجموع تمام ردیف\u200cها (مبلغ اصلی + کارمزد)', verbose_name='مبلغ کل (ریال)')),
                ('raw_callback_data', models.JSONField(blank=True, null=True, verbose_name='پاسخ خام بانک')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید نهایی')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.ordermodel', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('principal', 'مبلغ اصلی'), ('commission', 'کارمزد')], max_length=20, verbose_name='نوع ردیف')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='transactions.transactioans', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'ردیف تراکنش',
                'verbose_name_plural': 'ردیف\u200cهای تراکنش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactioans',
            index=models.Index(fields=['authority'], name='idx_transaction_authority'),
        ),
        migrations.AddIndex(
            model_name='transactioans',
            index=models.Index(fields=['status'], name='idx_transaction_status'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionentry',
            unique_together={('transaction', 'entry_type')},
        ),
    ]
