# Generated by Django 6.0.6 on 2026-07-26 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discountmodel_productsmodel_file_commentsmodel_and_more'),
        ('users', '0004_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.productsmodel', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
