# Generated by Django 6.0.6 on 2026-07-26 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discountmodel_productsmodel_file_commentsmodel_and_more'),
        ('users', '0005_alter_userorder_product_alter_userorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='products',
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد محصولات')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.cartmodel', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': ' سبد ',
                'verbose_name_plural': 'سبد ',
                'ordering': ('-created_at',),
            },
        ),
    ]
