# Generated by Django 6.0.6 on 2026-07-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_cartmodel_products_cartitemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='total',
        ),
    ]
