# Generated by Django 6.0.6 on 2026-07-26 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discountmodel_productsmodel_file_commentsmodel_and_more'),
        ('users', '0007_remove_cartmodel_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(help_text='Unique order number.', max_length=30, unique=True, verbose_name='شماره سفارش')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price of the order.', max_digits=12, verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('COMPLETED', 'تکمیل شده'), ('CANCELED', 'لغو شده')], default='PENDING_PAYMENT', help_text='Current order status.', max_length=20, verbose_name='وضعیت سفارش')),
                ('user', models.ForeignKey(help_text='Owner of this order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Purchased quantity.', verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price at purchase time.', max_digits=12, verbose_name='قیمت')),
                ('product', models.ForeignKey(help_text='Purchased product.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productsmodel', verbose_name='محصول')),
                ('order', models.ForeignKey(help_text='Related order.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.ordermodel', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
