# Generated by Django 6.0.6 on 2026-07-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discountmodel_productsmodel_file_commentsmodel_and_more'),
        ('users', '0008_ordermodel_orderitemmodel_delete_userorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_number',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.discountmodel'),
        ),
    ]
